baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Mr. Growing's journal"
theme = "whiteplain"
copyright = "&copy; Copyright 2024 xxx.github.io"

[[menu.main]]
identifier = "all"
name = "All Posts"
url = "/"
weight = 1

[[menu.main]]
identifier = "journal"
name = "Journal"
url = "/journal/"
weight = 2


[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3


[taxonomies]
tag = "tags"
series = "series"
category = "categories"

[params]
showShareIcons = false
